# Generated by Django 4.2 on 2026-02-02 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_price_100g_product_price_250g_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_100g',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_250g',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_500g',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_50g',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_kg',
        ),
        migrations.RemoveField(
            model_name='product',
            name='units',
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='📦', max_length=10),
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_label', models.CharField(max_length=20)),
                ('weight_grams', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_available', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='store.product')),
            ],
            options={
                'ordering': ['-weight_grams'],
                'unique_together': {('product', 'unit_label')},
            },
        ),
    ]
