# Generated by Django 4.2 on 2026-04-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_category_options_remove_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
