# Generated by Django 4.2 on 2026-06-03 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_staffprofile_order_assigned_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffProfile',
        ),
    ]
