# Generated by Django 4.2 on 2026-06-03 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_delete_staffprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
    ]
